### ISSUE TITLE
Fresh instance: Creating a project results in error 500

### ISSUE THREAD

**Issue by ab-smith** [intuitem/mira-community#18]
**Describe the bug**
missing error management

**To Reproduce**
1. fresh instance, no domain created yet
2. create a new project -> we see undefined on domain

**Expected behavior**
- better error management

**Screenshots**
<img width="593" alt="image" src="https://github.com/intuitem/mira-community/assets/11318384/acaa3f74-7d35-4ed3-89e5-315db86af29b">

**Comment by nas-tabchiche** [comment]
This affects projects and security measures. Cooking a PR to fix this
